### ISSUE TITLE
Análisis de resultados robo casa habitación y robo transeúnte

### ISSUE THREAD

**Issue by cbautistap** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-JSOHE#18]
- [x] Robo casa habitación
- [x] Robo transeúnte

**Comment by vserranoc** [comment]
En el caso del robo a transeúnte los factores que influyen en este tipo de delito son distintos a los señalados para el robo a casa habitación. Para conocer las variables que afectan este delito tendría que realizarse una revisión de literatura y buscar otras variables. Se incluye el ejercicio como anexo para mostrar que los factores que influyen en este delito difieren de los detectados para robo a casa habitación.
