### ISSUE TITLE
Base

### ISSUE THREAD

**Issue by JSOHE** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-JSOHE#2]
- [x] subir la base

- [x] limpiar la base eliminando acentos y ñ

- [ ] empezar la descripción del documento "introducción en latex"

- [x] transformar la base a una por año y entidad

**Comment by vserranoc** [comment]
Se agrega base de datos

**Comment by cbautistap** [comment]
La base de datos está limpia y lista para usarse. Se llama base_final.csv y está en master
